TPaste/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from Paste.views import (
    DetailPasteView,
    DetailPasteRawView,
    # DetailPasteEmbedView,
    AboutView,
    ProfileContainerView,
    IndexView,
    DeletedView,
    PrivacyView,
    ProtectedView,
    DisclaimerView,
    # ApiLoginView,
    UserPasteChangeView,
    # PasteSerializerCreate,
    ContentSearchView,
    ReportView,
    TermsView,
    ProfileDetailsView,
    ContactView
)
from allauth.account.views import (
    PasswordChangeView,
    EmailView,
)

from django.contrib.sitemaps.views import sitemap
from Paste.sitemap import PasteSitemap

sitemaps = {
    'static': PasteSitemap,
}

L = getattr(settings, 'SLUG_LENGTH', 4)

urlpatterns = [

    # Main
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^{}/'.format(settings.ADMIN_URL), admin.site.urls),
    url(r'^$', IndexView.as_view(), name='paste_new'),
    url(r'^About/$', AboutView.as_view(), name='about'),
    url(r'^Privacy/$', PrivacyView.as_view(), name='privacy'),
    url(r'^terms_of_service/$', TermsView.as_view(), name='terms_of_service'),
    url(r'^Disclaimer/$', DisclaimerView.as_view(), name='disclaimer'),

    # Sitemap
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # REST Api User Logic
    # ---------------------------------------------------
    # ---------------------------------------------------
    # url(r'^Api/v1/Login/$', ApiLoginView.as_view(), name='rest_login'),
    # url(r'^Api/v1/New/$', PasteSerializerCreate.as_view(), name='paste_api_create_new'),

    # Static Areas
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^ChangeLog/$', TemplateView.as_view(template_name="changelog.txt", content_type="text/plain"), name='changelog'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^License/$', TemplateView.as_view(template_name="license.txt", content_type="text/plain"), name="license_file"),

    # Social Login Partial
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^accounts/', include('allauth.urls')),

    # Email
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r"^email/$", EmailView.as_view(template_name="pages/profile/profile_details.html", success_url='/accounts/profile/'), name="account_email"),
    url(r"^password/change/$", PasswordChangeView.as_view(template_name='pages/profile/profile_details.html', success_url='/accounts/profile/'),name="account_change_password"),

    # Other Function Areas
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^Search', ContentSearchView.as_view(), name='search'),
    url(r'^Report', ReportView.as_view(), name='paste_report_view'),
    url(r'^Contact', ContactView.as_view(), name='contact_view'),
    url(r'^accounts/container/$', ProfileContainerView.as_view(), name='linkler'),
    url(r'^accounts/profile/$', ProfileDetailsView.as_view(), name='profil_details_view'),

    # Functions
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^(?P<auth_id>[a-fA-F0-9]{32})/Delete/$', DeletedView.as_view(), name='sil'),
    url(r'^(?P<auth_id>[a-fA-F0-9]{32})/Change/$', UserPasteChangeView.as_view(), name='degistir'),

    # Show Pastes
    # ---------------------------------------------------
    # ---------------------------------------------------
    url(r'^(?P<paste_id>[a-zA-Z0-9]{%d,})/Protected/' % L, ProtectedView.as_view(), name='protect'),
    url(r'^(?P<paste_id>[a-zA-Z0-9]{%d,})/$' % L, DetailPasteView.as_view(), name='paste_details'),
    url(r'^(?P<paste_id>[a-zA-Z0-9]{%d,})/Raw/$' % L, DetailPasteRawView.as_view(), name='paste_details_raw'),
    #url(r'^Embeded/(?P<paste_id>[a-zA-Z0-9]{%d,})' % L, DetailPasteEmbedView.as_view(), name='paste_details_embed'),
]

Paste/forms.py
from django import forms
from django.core.validators import RegexValidator
from Paste.highlight import LEXER_CHOICES
from django.forms.widgets import TextInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget
from snowpenguin.django.recaptcha2.widgets import ReCaptchaHiddenInput

from allauth.account.forms import (
    SignupForm,
    LoginForm,
    ResetPasswordForm,
)

CONTACT_CHOICES = (
    ('telif_ihlali', _('Güvenlik İhlali')),
    ('oneri', _('Öneri')),
    ('soru', _('Soru')),
    ('diger', _('Diğer'))
)

REASON_CHOICES = (
    ('gizlilik_ihlali', _('Gizlilik İhlali')),
    ('hak_ihlali', _('Haklarımı ihlal ediyor')),
    ('child_abuse', _('Çocuk istismarı')),
    ('terorism', _('Terörizmi teşvik ediyor')),
    ('spammer', _('Spam veya yanıltıcı içerik')),
    ('danger_content', _('Zarar verici tehlikeli hareketler')),
    ('nefret_soylemi', _('Nefret söylemi veya aşağılayıcı dil')),
    ('ataturke_abuse', _('Atatürk aleyhine işlenen suçlar')),
    ('uyusturucu_abuse', _('Uyuşturucu veya uyarıcı madde kullanılmasını kolaylaştırma')),
    ('intihar_abuse', _('İntihara yönlendirme')),
)

EXPIRE_CHOICES = (
    ('1h', _('Bir saat içinde yok et')),
    ('7d', _('Bir hafta içinde yok et')),
    ('30d', _('Bir ay içinde yok et')),
    ('never', _('Asla yok etme')),
)

PUBLIC_CHOICES = (
    (1, _('Genele Açık Paylaş')),
    (0, _('Paylaşma')),
)

EXPIRE_DEFAULT = 'never'
REASON_DEFAULT = 'spammer'
CONTACT_DEFAULT = 'soru'

LEXER_DEFAULT = '_code'
PUBLIC_DEFAULT = 1
LEXER_WORDWRAP = ('rst',)

"""
    yapıştırma içerik form alanı
"""


class PasteForm(forms.Form):
    status = forms.ChoiceField(
        choices=PUBLIC_CHOICES,
        initial=PUBLIC_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
    )

    lexer = forms.ChoiceField(
        choices=LEXER_CHOICES,
        initial=LEXER_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
    )

    expire = forms.ChoiceField(
        choices=EXPIRE_CHOICES,
        initial=EXPIRE_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
    )

    title = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'input', 'autocomplete': 'off',
                   'placeholder': 'İçeriğiniz için başlık girebilirsiniz'}),
    )

    content = forms.CharField(
        widget=Textarea(
            attrs={'class': 'textarea', 'rows': '10', 'maxlength': '262144000',
                   'placeholder': 'Yapıştırılacak içerik buraya gelecek...'}),
        required=True,
    )

    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'parola ile içerik koruma'}),
    )

    tags = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'input'}),
        validators=[RegexValidator('[a-zA-Z0-9]+', message='Sadece Alphanumeric', code='invalid_tags')]
    )

    def clean(self):
        cleaned_data = super(PasteForm, self).clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        tags = cleaned_data.get('tags')
        if len(title) > 160:
            raise ValidationError("Maximum 160 karakter girebilirsiniz.")
        if not content:
            raise ValidationError("İçerik girişi yapmalısınız.")
        if not tags:
            raise ValidationError("Etiket girişi yapmalısınız.")


"""
    içerik guncelleme form alanı
"""


class PasteUpdateForm(forms.Form):
    lexer = forms.ChoiceField(
        choices=LEXER_CHOICES,
        initial=LEXER_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
    )

    expire = forms.ChoiceField(
        choices=EXPIRE_CHOICES,
        initial=EXPIRE_DEFAULT,
        widget=Select(attrs={'class': 'input'})
    )

    content = forms.CharField(
        widget=Textarea(
            attrs={'class': 'textarea', 'rows': '20', 'placeholder': 'Yapıştırılacak içerik buraya gelecek...'}),
        label=_(u'İçerik'),
        required=True,
    )


"""
    parola korumalı yapıştırmalardaki form yapısı
"""


class ProtectedDatailViewForm(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaWidget())
    password = forms.CharField(
        label=_(u'Parola'),
        required=True,
        widget=forms.PasswordInput(attrs={'minlength': '4'}),
    )

    def clean(self):
        cleaned_data = super(ProtectedDatailViewForm, self).clean()
        password = cleaned_data.get('password')
        if len(password) < 4:
            raise ValidationError("Minimum 4 karakter girebilirsiniz.")
        if not password:
            raise ValidationError("Parola Girmelisiniz.")


"""
    Kötüye kullanım bildirme alanı form yapımız
"""


class ReportForm(forms.Form):
    rapor_nedeni = forms.CharField(
        widget=Textarea(
            attrs={'class': 'textarea', 'rows': '10', 'minlength': '40',
                   'placeholder': 'Kötüye kullanım bildirme nedeniniz'}),
        required=True,
    )

    reason = forms.ChoiceField(
        choices=REASON_CHOICES,
        initial=REASON_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
        required=True,
    )

    mail = forms.CharField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'input', 'placeholder': 'Mail adresiniz'}),
    )

    slugs_id = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'input'}),
    )

    captcha = ReCaptchaField(widget=ReCaptchaWidget())


"""
    İletişim formunda kullanılacak yapı
"""


class ContactForm(forms.Form):
    ad_soyad = forms.CharField(
        widget=TextInput(
            attrs={'class': 'input', 'maxlength': '160',
                   'placeholder': 'Adınız ve Soyadınız'}),
        required=True,
    )

    iletisim_nedeni = forms.ChoiceField(
        choices=CONTACT_CHOICES,
        initial=CONTACT_DEFAULT,
        widget=Select(attrs={'class': 'input'}),
    )

    mail = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'input', 'placeholder': 'Mail adresiniz'}),
        required=True,
    )

    aciklama = forms.CharField(
        widget=Textarea(
            attrs={'class': 'textarea', 'rows': '10', 'minlength': '10',
                   'placeholder': 'Mesajınız'}),
        required=True,
    )

    captcha = ReCaptchaField(widget=ReCaptchaWidget())


# ---------------------------------------------
# Recaptcha
# ---------------------------------------------

class MyCustomLoginForm(LoginForm):
    captcha = ReCaptchaField(widget=ReCaptchaWidget())


class MyCustomSignupForm(SignupForm):
    captcha = ReCaptchaField(widget=ReCaptchaWidget())


class MyCustomResetPasswordForm(ResetPasswordForm):
    captcha = ReCaptchaField(widget=ReCaptchaWidget())

templates/pages/about.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %} {% trans 'Yapıştır.io! - Hakkında' %} {% endblock %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-two-thirds">
                    <div class="content">
                        <h1 class="title">{% trans 'Yapıştır.io Hakkında' %} </h1>
                        <p>{% trans 'Yapıştırma servisimiz bir takım sürdürülebilirlik sorunlarından kurtulmak, kısıtlamaları ortadan kaldırmak ve can sıkıntımızı gidermek için geliştirilmiştir.' %}</p>
                        <h3> {% trans 'Alt Yapımız' %} </h3>
                        <p>{% trans 'Uygulamamızı oluştururken kullandıklarımız' %}</p>
                        <ul>
                            <li><b>{% trans 'Yazılım iskeleti:' %}</b> Django</li>
                            <li><b>{% trans 'Programlama dili:' %}</b> Python, JavaScript</li>
                            <li><b>{% trans 'Front-end:' %}</b> Bulma CSS</li>
                            <li><b>{% trans 'Editör:' %}</b> Custom</li>
                            <li><b>{% trans 'Vurgulama:' %}</b> Pygments</li>
                            <li><b>{% trans "Fontlar:" %}</b> Font Awesome</li>
                            <li><b>{% trans 'WSGI sunucusu:' %}</b> UWSGI</li>
                            <li><b>{% trans 'Web server:' %}</b> Nginx</li>
                            <li><b>{% trans 'Veritabanı:' %}</b> Postgresql</li>
                            <li><b>{% trans 'İçerik ID:' %}</b> SystemRandom</li>
                            <li><b>{% trans 'İşletim sistemi:' %}</b> Debian</li>
                            <li><b>{% trans 'Hata takip:' %}</b> Sentry</li>
                            <li><b>{% trans 'Dil desteği:' %}</b> Turkish, English</li>
                            <li><b>{% trans 'Sağlayıcı:' %}</b> Hetzner Online GmbH</li>
                        </ul>
                        <p><b>{% trans 'Kaynak Kodlar:' %}</b> YAKINDA</p>
                        <br>
                        <p><b>{% trans 'Güncellemeler:' %}</b> <a
                                href=" {% url 'changelog' %} "> {% trans 'Değişiklik Günlüğü' %} </a></p>
                    </div>
                </div>
                <div class="column">
                    <h1 class="title">{% trans 'İstatistikler' %}</h1>
                    <p><strong>{{ total }}</strong> {% trans 'Adet içerik veritabanımızda bulunmaktadır.' %}</p>
                    <a href="https://www.hetzner.com/" target="_blank"
                       title="Hetzner Online offers professional hosting solutions for a fair price."><img
                            src="{% static "images/hetzner-hosted-201.gif" %}" alt="Hetzner Online"></a>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/pages/index.html
{% extends "base.html" %}

{% load recaptcha %}
{% load i18n %}
{% load static %}

{% block title %} {% trans 'Yapıştırma Servisi - Yapıştır.io!' %}{% endblock %}
{% block description %}Yapistir.io text ve kodlarınızı belirli bir süre için çevrimiçi olarak saklayabileceğiniz bir web
    sitesidir.{% endblock description %}

{% block seo %}
    <script type="application/ld+json">
            {
            "@context": "http://schema.org",
            "@type": "WebSite",
            "url": "https://yapistir.io",
                "potentialAction": {
                    "@type": "SearchAction",
                    "target": "https://yapistir.io/Search?q={q}",
                    "query-input": "required name=q"
                }
            }
    </script>
    <meta property='og:locale' content='tr_TR'/>
    <meta property="og:site_name" content="Yapistir.io"/>
    <meta property="fb:app_id" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://yapistir.io/"/>
    <meta property="og:title" content="Yapistir.io"/>
    <meta property="og:description"
          content="Yapistir.io text ve kodlarınızı belirli bir süre için çevrimiçi olarak saklayabileceğiniz bir web sitesidir."/>
    <meta name="twitter:site" content="@horusteknoloji"/>
    <meta name="twitter:site:id" content=""/>
    <meta name="twitter:creator" content="@horusteknoloji"/>
    <meta name="twitter:creator:id" content=""/>
    <meta name="twitter:url" content="https://yapistir.io/"/>
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="Yapistir.io"/>
    <meta name="twitter:description"
          content="Yapistir.io text ve kodlarınızı belirli bir süre için çevrimiçi olarak saklayabileceğiniz bir web sitesidir."/>
{% endblock seo %}

{% block js_header %}
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/bulma-tagsinput.min.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/codemirror.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.40.0/codemirror.min.js"></script>
    <style>
        .CodeMirror {
            border: 1px solid #ddd;
        }
    </style>
{% endblock js_header %}

{% block content %}
    <form method="POST" action="." name="pasteform" novalidate>
        {% csrf_token %}
        <div class="field">
            <label class="label">İçerik</label>
            <div class="control">
                {{ form.content }}
            </div>
        </div>
        <div class="tile is-ancestor">
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">Başlık:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="is-fullwidth">
                                        {{ form.title }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">Vurgulama:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="select is-fullwidth">
                                        {{ form.lexer }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="field is-horizontal">
                            <div class="field-label">
                                <label class="label">Silineceği Tarih:</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <div class="select is-fullwidth">
                                            {{ form.expire }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="field is-horizontal">
                            <div class="field-label">
                                <label for="id_expire" class="label">Geçerlilik:</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <div class="select is-fullwidth">
                                            <select name="expire" class="input" id="id_expire">
                                                <option value="30d">Bir ay içinde yok et</option>
                                                <option value="never" selected>Asla yok etme</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">Listede Paylaş:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="select is-fullwidth">
                                        {{ form.status }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="field is-horizontal">
                            <div class="field-label">
                                <label class="label">Parola:</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <div class="is-fullwidth">
                                            {{ form.password }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                    {% endif %}

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">Etiketler:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="is-fullwidth">
                                        <input class="input" name="tags" id="tags" type="tags"
                                               placeholder="etiketler" data-tags-delimiters="enter,space,comma"
                                               required>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if not user.is_authenticated %}
                        <div class="field">
                            <div class="control">
                                {% recaptcha %}
                            </div>
                        </div>
                    {% endif %}
                    <div class="field">
                        <div class="control">
                            <button class="button is-block is-info is-large is-fullwidth" type="submit" id="submit">
                                <i class="far fa-save"></i> Kaydet
                            </button>
                        </div>
                    </div>
                </article>
            </div>
            <div class="tile is-parent">
                <div class="column">
                    <table class="table is-fullwidth">
                        <thead>
                        <tr>
                            <th>Son Yayınlananlar</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for pub in publics %}
                            <tr>
                                <td> {% if pub.title %} <a href="{{ pub.slug }}">{{ pub.title }}</a> {% else %}
                                    <a href="{{ pub.slug }}">Başlıksız</a> {% endif %} </td>
                                <td>{{ pub.publish|timesince }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
    {% for message in messages %}
        <div class="container">
            <div class="columns is-fullwidth">
                <div class="column">
                    <div class="notification {% if message.tags %} is-{{ message.tags }}{% endif %}">
                        <button class="delete"></button>
                        {{ message|safe }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include "include/__errors.html" %}
{% endblock %}

{% block js_code %}
    <script src="{% static "assets/js/bulma-tagsinput.min.js" %}"></script>
    <script>
        bulmaTagsinput.attach();
    </script>

    <script>
        let editor = CodeMirror.fromTextArea(document.getElementById("id_content"), {
            lineNumbers: true,
            matchBrackets: true
        });
    </script>
{% endblock js_code %}

templates/pages/report_area.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load recaptcha2 %}

{% block title %} {{ request.META.HTTP_REFERER }} - Report {% endblock %}

{% block js_header %}
    {% recaptcha_init 'tr' %}
{% endblock js_header %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-two-fifths">
                    <div class="content">
                        <h2 class="title">{% trans "Kötüye Kullanımı Bildir" %}</h2>
                        <br>
                        <p class="subtitle">{% trans "Platformumuz herkes için güvenli olmalı, bu yüzden yapistir_io'da istismar ve tacizleri ciddiye alıyoruz." %}</p>
                        <p>{% trans "Sitede" %} <a href="{% url 'terms_of_service' %}"> hizmet
                            şartları’nı</a> {% trans "ihlal eden zararlı davranışları tespit etmek istiyoruz. İlgilendiğiniz kullanıcının içeriğini bize bildirin." %}
                        </p>
                        <h3 class="title">{% trans "Kötüye Kullanım Bildirirken" %}</h3>
                        <ul>
                            <li> {% trans "Temiz ve anlaşılır bir dil kullanın" %}</li>
                            <li> {% trans "Geçerli sebepler sunun" %} </li>
                            <li> {% trans "Mümkünse görseller ile destekleyin" %} </li>
                            <li> {% trans "Sabırlı olun" %} </li>
                        </ul>
                        <p>{% trans "Kötüye kullanım bildirdiğiniz andan itibaren, 24-48 saat içerisinde mail adresinize gerekli geri dönüş sağlanacaktır." %}</p>
                        <article class="message is-danger">
                            <div class="message-header">
                                <p> {% trans "DİKKAT" %} </p>
                            </div>
                            <div class="message-body">
                                {% trans "Bilgilerinizi gizli tutacağımızdan emin olabilirsiniz" %}
                            </div>
                        </article>
                    </div>
                </div>
                <div class="column is-two-thirds">
                    <div class="field">
                        <div class="level">
                            <div class="level-left">
                            </div>
                            <div class="level-right">
                                <a class="button is-info is-outlined"
                                   href="{{ request.META.HTTP_REFERER }}"><i class="fas fa-arrow-left"></i>&nbsp;Geri Dön
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <form action="{% url 'paste_report_view' %}" method="POST">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                                <div class="field">
                                    <div class="control">
                                        <label class="label">Mail adresiniz:</label>
                                        <input type="email" class="input" name="mail"
                                               value="{{ request.user.email }}"
                                               readonly>
                                    </div>
                                </div>
                            {% else %}
                                <div class="field">
                                    <div class="control">
                                        <label class="label">Mail adresiniz:</label>
                                        {{ form.mail }}
                                    </div>
                                </div>
                            {% endif %}
                            <div class="field">
                                <div class="control">
                                    <label class="label">Kötüye kullanım bildirilecek bağlantı:</label>
                                    <input type="text" class="input" name="slugs_id"
                                           value="{{ request.META.HTTP_REFERER }}"
                                           readonly>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    <label class="label">Kötüye kullanım alt nedeni:</label>
                                    <div class="select is-fullwidth">
                                        {{ form.reason }}
                                    </div>
                                </div>
                            </div>
                            <div class="field">
                                <label class="label">Açıklama:</label>
                                <div id="textarea_feedback"></div>
                                <div class="control">
                                    {{ form.rapor_nedeni }}
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    {{ form.captcha }}
                                </div>
                            </div>
                            <button type="submit"
                                    class="button is-block is-info is-large is-fullwidth">{% trans "Kötüye Kullanım Bildir" %}
                            </button>
                        </form>
                        {% for message in messages %}
                            <div class="is-fullwidth">
                                <div class="column">
                                    <div class="notification {% if message.tags %} is-{{ message.tags }}{% endif %}">
                                        <button class="delete"></button>
                                        {{ message|safe }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block js_code %}
    <script>
        $(document).ready(function () {
            let text_max = 40;
            $('#textarea_feedback').html('Minimum ' + text_max + ' karakter');

            $('#id_rapor_nedeni').keyup(function () {
                let text_length = $('#id_rapor_nedeni').val().length;
                let text_remaining = text_max - text_length;

                $('#textarea_feedback').html('Minimum ' + text_remaining + ' karakter');
            });
        });
    </script>
{% endblock js_code %}